steps:
  # 1) Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/trello-clone-front/$BRANCH_NAME:$SHORT_SHA
      - .

  # 2) Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/trello-clone-front/$BRANCH_NAME:$SHORT_SHA

  # 3) Deploy al mismo servicio, revisiones únicas por rama y commit
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -e



        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Deploying MAIN branch..."
          gcloud run deploy trello-clone-front \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/trello-clone-front/$BRANCH_NAME:$SHORT_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --tag=$(printf '%s' "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9-]/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g' \
          | cut -c1-63) \
            --revision-suffix="${SHORT_SHA}"

          # Mover todo el tráfico a la última revisión de main
          gcloud run services update-traffic trello-clone-front \
            --region us-central1 \
            --to-latest
        else
          echo "Deploying FEATURE branch: $BRANCH_NAME"
          gcloud run deploy trello-clone-front \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/trello-clone-front/$BRANCH_NAME:$SHORT_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --tag=$(printf '%s' "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9-]/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g' \
          | cut -c1-63) \
            --revision-suffix="$(printf '%s' "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9-]/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g' \
          | cut -c1-63)-${SHORT_SHA}" \
            --no-traffic
        fi

        echo "URL principal: $(gcloud run services describe trello-clone-front --region us-central1 --format='value(status.url)')"
        echo "URL de esta rama: https://$(printf '%s' "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' \
          | sed -E 's/[^a-z0-9-]/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g' \
          | cut -c1-63)---$(
          gcloud run services describe trello-clone-front --region us-central1 --format='value(status.url)' | sed -E 's#^https?://##'
        )"

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/trello-clone-front/$BRANCH_NAME:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
